---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=0 #It depends (example: PUID=1000)
      - PGID=0 #It depends (example: PGID=1000)
      - TZ=Asia/Dhaka
    volumes:
      - /var/lib/docker/volumes/obsidian:/config #Create a folder on your local storage to sync with obsidian and this will store your data
    ports:
      - 3000:3000 #Internal port expose for internal communication
      - 3001:3001 #External port expose for web UI
    #devices:
    # - /dev/dri:/dev/dri #optional
    shm_size: "1gb"
    restart: unless-stopped
