---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asian/Dhaka
    volumes:
      - /var/lib/docker/volumes/syncthing:/config #Change this as per your system requirements 
      - /var/lib/docker/volumes/obsidian/mimnets:/obsidian #Change this as per your system requirements
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
