---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=0 #It depends (example: PUID=1000)
      - PGID=0 #It depends (example: PGID=1000)
      - TZ=Asia/Dhaka
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    #devices:
    # - /dev/dri:/dev/dri #optional
    shm_size: "1gb"
    restart: unless-stopped
