---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000 #It depends - Check by id 
      - PGID=1000 #It depends - Check by id -u
      - TZ=Asia/Dhaka
    volumes:
      - /var/lib/docker/volumes/obsidian:/config #Create a folder on your local storage to sync with obsidian and this will store your data
    ports:
      - 3000:3000 #External port expose for web UI
      - 3001:3001 #Internal port expose for internal communication
    #devices:
    # - /dev/dri:/dev/dri #optional
    shm_size: "1gb"
    restart: unless-stopped
